### ISSUE TITLE
为什么会挂呀？

### ISSUE THREAD

**Issue by swxca** [webbought/imoocDownloader#1]
![image](https://cloud.githubusercontent.com/assets/11407831/15316462/ab23934a-1c4f-11e6-9777-629dd6820c42.png)
![image](https://cloud.githubusercontent.com/assets/11407831/15316706/ba4fa240-1c50-11e6-8e5a-f7a1c0aef7d9.png)

**Comment by t2krew** [comment]
你npm install 了吗？

**Comment by swxca** [comment]
安装了，是不是我的node或者npm的依赖有问题。安装完之后报了警告。

**Comment by t2krew** [comment]
你换4.x的版本试试
