### ISSUE TITLE
课程目录列表

### ISSUE THREAD

**Issue by ghost** [webbought/imoocDownloader#10]
课程目录列表保存 一个课程保存一个文本或者图片

**Comment by t2krew** [comment]
@yakirChen 你是想生成个目录文件是吧？

**Comment by t2krew** [comment]
@yakirChen 已经加上 生成课程目录文本

**Comment by t2krew** [comment]
@yakirChen 
![image](https://cloud.githubusercontent.com/assets/5849474/18750833/5cb7911e-810f-11e6-9a76-80e041978ba0.png)

**Comment by ghost** [comment]
thanks 啦 多谢奉献
