### ISSUE TITLE
更新了sierraMac以后，运行要用sudo

### ISSUE THREAD

**Issue by wayson** [webbought/imoocDownloader#11]
昨天更新到sierra Mac，发现运行的时候不加sudo，就会报错。

**Comment by t2krew** [comment]
@wayson 你在什么路径里执行？

**Comment by wayson** [comment]
/Users/waysonlin/Documents/workspace/nodejs/imoocDownloader

**Comment by ChinaHackers** [comment]
How to use under the sierra

**Comment by quworld** [comment]
node index.js --search mongodb 为什么运行这条命令的时候，会报下面这个错误：
imoocDownloader/index.js:4
    logger.error(err);
          ^

TypeError: Cannot read property 'error' of undefined
    at process.<anonymous> (/Users/hofoo/Soft/common/imoocDownloader/index.js:4:11)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:224:26)

**Comment by t2krew** [comment]
@quworld  更新下新版代码再试试看
