### ISSUE TITLE
下载出来的不是视频文件

### ISSUE THREAD

**Issue by Lnybb** [webbought/imoocDownloader#12]
RT

**Comment by t2krew** [comment]
@Lnybb 不会呀，刚测了下，是可以下载的。是不是你指定的课程id有误？

**Comment by Lnybb** [comment]
![1](https://cloud.githubusercontent.com/assets/12817197/21073105/fac94e9e-bf10-11e6-84b7-130bbbaf4cc3.png)

![2](https://cloud.githubusercontent.com/assets/12817197/21073087/d1433f62-bf10-11e6-8a1d-95c9eb7b1784.png)

![3](https://cloud.githubusercontent.com/assets/12817197/21073099/d4e837f8-bf10-11e6-9db5-481c3f835d57.png)

**Comment by t2krew** [comment]
@Lnybb 你重新update新版本试试，如果没有猜错的话，应该是windows系统下文件名不支持带有:（冒号），所以:之后的字符都没有了，所以就后缀名也就没了导致文件格式有误。改了下代码，但因为我这边没有windows机，所以测不了，你可以update一下代码，看可以了没。如果还是不行，你可以手动修改一下文件的后缀名为.mp4，应该就可以了。

**Comment by Lnybb** [comment]
额，两种方式都试了试，还是不行。。。

**Comment by t2krew** [comment]
@Lnybb  你再更新下代码版本试试，昨天改的时候正则写错符号了，刚有位朋友提了pr，你可以再试试。

**Comment by Lnybb** [comment]
可以啦，感谢付出！

**Comment by Lnybb** [comment]
变成可视化的工具就更NB了

**Comment by t2krew** [comment]
@Lnybb 哈哈你这个想法可以自己尝试实现一下
