### ISSUE TITLE
程序能跑，但会出现卡住的情况

### ISSUE THREAD

**Issue by Utobehabe** [webbought/imoocDownloader#17]
![image](https://cloud.githubusercontent.com/assets/20036273/21103708/868dd78e-c0be-11e6-9f8f-a0d25a64eb75.png)
之前试了一下是没问题的，今天下午下视频的时候下到一半就出现上面的那种情况了，进度卡住，程序不会往下走

**Comment by t2krew** [comment]
@Utobehabe 可能是网络问题，多试几下看看。

**Comment by t2krew** [comment]
@Utobehabe   前面有一个朋友也提了个issue #16 `Error: read ECONNRESET`，有可能是慕课网那边的网络不稳定
