### ISSUE TITLE
你抓这个视频不需要模拟登入么

### ISSUE THREAD

**Issue by fanne** [webbought/imoocDownloader#18]
我是用python在抓的，但有个登入问题卡住我了，他们在post密码的时候，对密码进行了加密，每次得到的那串加密字符串都不一样，所以卡住没有登入，不知你用node.js怎么解决的，还不需要处理登入问题。

**Comment by t2krew** [comment]
@fanne 不需要登录，你可以在浏览器端登录之后去查看视频，可以发现他们的规律，直接利用规律下载就行了。他的视频源是调用ajax获取到视频链接的，所以呢直接去调用那个ajax就可以拿到视频信息了。
