### ISSUE TITLE
请问目前的爬虫还能用吗？

### ISSUE THREAD

**Issue by joriscai** [webbought/imoocDownloader#4]
我现在在用爬虫下载时，老是一开始就很快，到了后面就下载很慢或者下载不了？是不是慕课网的策略调整？还是我的运行环境问题或线路问题？求大家测试一下，谢谢！

**Comment by t2krew** [comment]
刚测试完，还可以下载，应该是你那边的网络问题

**Comment by joriscai** [comment]
@webbought 用网站缓冲的话，缓冲速度挺快的，但是用工具下载就很慢了，是不是工具的原因呢？

**Comment by jovey-zheng** [comment]
@joriscai 工具是正常网络请求，没有做多余的网络处理，你可以换另外一台机器试一下

**Comment by joriscai** [comment]
@jovey-zheng 你能提供一下你的nodejs版本号给我吗？我有怀疑是我的nodejs版本问题

**Comment by jovey-zheng** [comment]
@joriscai `4.x+`
